from .Animal import Animal
from .Animal import Chicken
from .Animal import Cow
from .Animal import Deer
from .Animal import Fox
from .Animal import Rabbit
from .Animal import Zubr
from .Background import Background
from .Bubble import Bubble
from .Button import Button
from .Ufo import Ufo